[project]
name = "vapi-voice-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "ngrok>=1.4.0",
    "pyngrok>=8.1.2",
    "sqlalchemy>=2.0.52",
    "streamlit>=1.63.0",
    "uvicorn>=0.52.4",
]
